services:
  - type: web
    name: heart-disease-detector
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12
    plan: starter

databases:
  - name: heart-disease-db
    databaseName: heartfelt
    user: heartfelt_user
    plan: starter
